// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:kids_tracker/core/db/location_hive_model.dart';
import 'package:kids_tracker/core/db/setting_hive_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(LocationHiveModelAdapter());
    registerAdapter(SettingHiveModelAdapter());
  }
}
